# Hyperparameters and ResNet18 from on https://arxiv.org/abs/2012.0611

BASE_TASK_CONFIG_PATH: "configs/tasks/roomnav.yaml"
TRAINER_NAME: "ddppo"
ENV_NAME: "RoomNavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
# Can be uncommented to generate videos.
VIDEO_OPTION: ["disk"]
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir"
# Evaluate on all episodes
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "checkpoints/ckpt.1.pth"
NUM_ENVIRONMENTS: 1
SENSORS: ["DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "checkpoints"
TOTAL_NUM_STEPS: -1.0
LOG_INTERVAL: 10
NUM_CHECKPOINTS: 10
NUM_UPDATES: 10
FORCE_TORCH_SINGLE_THREADED: True


RL:
  SUCCESS_REWARD: 2.5

  POLICY:
    name: "PointNavResNetPolicy"

  PPO:
    # ppo params
    clip_param: 0.2
    ppo_epoch: 2
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.2
    num_steps: 128
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    reward_window_size: 50

    use_normalized_advantage: False

    hidden_size: 512

    # Use double buffered sampling, typically helps
    # when environment time is similar or large than
    # policy inference time during rollout generation
    use_double_buffered_sampler: False

  DDPPO:
    sync_frac: 0.6
    # The PyTorch distributed backend to use
    distrib_backend: NCCL
    # Visual encoder backbone
    pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
    # Initialize with pretrained weights
    pretrained: False
    # Initialize just the visual encoder backbone with pretrained weights
    pretrained_encoder: False
    # Whether or not the visual encoder backbone will be trained.
    train_encoder: True
    # Whether or not to reset the critic linear layer
    reset_critic: True

    # Model parameters
    backbone: resnet50
    rnn_type: LSTM
    num_recurrent_layers: 2
