ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0

  SENSORS: [ 'ROOMGOAL_SENSOR', 'GPS_SENSOR', 'COMPASS_SENSOR']
  ROOMGOAL_SENSOR:
    TYPE: RoomGoalSensor
  GOAL_SENSOR_UUID: "roomgoal"

  MEASUREMENTS: ['ROOMNAVMETRICPOINT', 'ROOMSUCCESS']
  ROOMNAVMETRICPOINT:
    TYPE: RoomNavMetricPoint
  METRIC_UUID: "roomnavmetricpoint"

DATASET:
  TYPE: RoomNav-v1
  SPLIT: val
  DATA_PATH: data/beacon/v0/{split}/content/beacon-7-untrimmed.json.gz
  SCENES_DIR: "data/scene_datasets/"

